#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ load("secret.lib.yml", "secret")

#@ def pod_labels():
app: uaa
#@ end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaa
  template:
    metadata:
      labels: #@ pod_labels()
    spec:
      containers:
      - name: uaa
        image: #@ "{}/uaa{}".format(data.values.repository, data.values.image_suffix.uaa)
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: uaa-config-volume
          mountPath: /uaa
        env:
        - #@ secret("DB_ENV_USER", "db_username")
        - #@ secret("DB_ENV_PASS", "db_password")
        - #@ secret("ENCRYPTION_PASSPHRASE", "encryption_passphrase")
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: uaa-signing-key-secret
              key: tls.key
        - name: SAML_PROVIDER_CERT
          valueFrom:
            secretKeyRef:
              name: uaa-saml-cert-secret
              key: tls.crt
        - name: SAML_PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              name: uaa-saml-cert-secret
              key: tls.key
      volumes:
      - name: uaa-config-volume
        configMap:
          name: uaa-config
---
apiVersion: v1
kind: Service
metadata:
  name: uaa-service
spec:
  selector: #@ pod_labels()
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
