#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:assert", "assert")

#@ load("secret.lib.yml", "resource_name")

apiVersion: v1
kind: Secret
metadata:
  name: #@ resource_name
type: Opaque
data:
  db_username: #@ base64.encode(data.values.database.username)
  db_password: #@ base64.encode(data.values.database.password or assert.fail("missing password"))
  encryption_passphrase: #@ base64.encode(data.values.encryption_passphrase or assert.fail("missing encryption_passphrase"))
